version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
            - pip install pytest
            - pip install pytest-cov
            - pip install mixer
    pre_build:
        commands:
            - python --version
            - pytest
            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint $CODEBUILD_SRC_DIR/myproject/*py
artifacts:
    files:
        - '**/*'
