""" init documentation"""
    # Generated by Django 4.2 on 2023-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('userid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pet_id', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pet_type', models.CharField(default='Dog', max_length=30)),
                ('pet_breed', models.CharField(max_length=30)),
                ('pet_location', models.CharField(max_length=30)),
                ('pet_bloodline', models.CharField(max_length=30)),
                ('pet_nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pet_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_breed', models.CharField(max_length=30)),
                ('pet_location', models.CharField(max_length=30)),
                ('pet_bloodline', models.CharField(max_length=30)),
                ('pet_nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pet_rem', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pet_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
